version: '3.8'

services:
    postgres:
        image: postgres:latest
        hostname: postgres-db
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            PGADMIN_THEME: dark
        ports:
            - "8081:80"
        depends_on:
            - postgres
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    postgres-data:
    pgadmin-data:
